#!/bin/bash

[ -z $1 ] && { echo $0: missing operand; exit 1; }

path="$1"

if [ "${path:0:1}" != / ]; then
    dir=$(dirname "$path")
    if [ -d "$dir" ]; then
        path="$(cd $dir; pwd)/$(basename $path)"
    else
        path="${PWD}/$(sed -E 's-//+-/-g;s-/$--' <<<${path})"
    fi
fi

echo $path
