#!/bin/bash
# timechart: generate barcharts for a set of files generated by tabulate.sh

plotfile="/var/tmp/plotfile"
temp="/var/tmp/temp.dat"

for file in "$@"; do
    cat  > "$plotfile" <<HEAD
set style fill solid 0.25 border -1
set style boxplot outliers pointtype 7
set style data boxplot
set datafile separator '\t'
set nokey

set ylabel "Time / s"

plot "$temp" using (1):1:(0.5):2
HEAD

    awk 'BEGIN {OFS="\t"}
    {
        name = $1
        gsub(/_/," ",name)
        for (i = 2; i <= NF; ++i) {
            printf("%g\t\"%s\"\n", $i, name)
        }
    }' $file > $temp

#   # transpose numeric columns
#   awk 'BEGIN { z = 0 }
#   {
#       lines[NR] = $0
#       z = z < NF ? NF : z
#   }
#   END {
#       for (j = 2; j <= z; ++j) {
#           for (i = 1; i <= NR; ++i) {
#               split(lines[i], line_i)
#               printf("%g\t",line_i[j])
#           }
#           printf("\n")
#       }
#   }
#   ' $file > $temp

    gnuplot -persist $plotfile
done
