#!/bin/bash

rebuild () {
    local proj_dir=$1
    make -C $proj_dir clean; make -C $proj_dir -j5 EXTRA_FLAGS=-pg COMPILER=intel
}

for dir in "$@"; do
    proj_dir="${dir}/epoch3d"
    [ -d "$proj_dir" ] || continue

    rebuild "${proj_dir}"
done
