#!/bin/bash

readonly PROGNAME="$(basename $0)"
readonly USAGE="Usage: $PROGNAME [-d] -n nodes -p ppn -m mem -t walltime -- root_dir"
err () {
    echo -e "$PROGNAME: $@" >&2; exit 1
}

name=$1
i=1
[ -z "$name" ] && err "missing operand\nTry \`$PROGNAME -h\' for more information."
[ ! -w "$(dirname $name)" ] && err "cannot create directory \`$name': Permission denied"

if [ ! -e $name ]; then
    mkdir $name
    echo $name
else
    until mkdir "${name}_"$i 2>&-; do
        i=$(($i + 1))
    done;
    echo ${name}_$i
fi
