#!/bin/bash
# avg.sh: generate barcharts of averages from output of tabulate.sh

width=0.5
plotfile="/var/tmp/plotfile"
temp="/var/tmp/temp.dat"

for file in "$@"; do
    cat  > "$plotfile" <<HEAD
set boxwidth $width
set style fill solid
set style line 1 lc rgb "#ff9999"
set style line 2 lc rgb "#dd8080"
set ylabel "Time / s"
set xlabel "Build"
set yrange [0:]
unset key

plot "$temp" u :2:xtic(1) w boxes ls 2, \
     "$temp" u :(20):2    w labels font ",8"
HEAD

    # add average to database
    awk '
    { 
        avg = 0
        for (i=2; i <= NF; ++i) {
            avg += $i
        }
        avg /= NF - 1
        gsub(/_/," ",$1)
        printf("\"%s\"\t%g\n", $1, avg)
    }
    ' $file \
        | sort -t $'\t' -k2n > $temp

    gnuplot -persist $plotfile
done
