#!/bin/bash

mutex_lock() {
    until mutex ${1:-lock}; do
        sleep 0.001
    done
}

function mutex() {
    mkdir ${1:-lock} 2>/dev/null
}

function mutex_unlock() {
    rmdir ${1:-lock} 2>/dev/null
}

tempdir=`mktemp --tmpdir=. -d`
labelfile=`mktemp --tmpdir=$tempdir`
trap 'rm -r "$tempdir"' EXIT
outfile="out"

while getopts ":o:" flag; do
    if [ $flag == 'o' ]; then
        outfile="$OPTARG"
    fi
done
shift $((${OPTIND} - 1))

echo > "$labelfile"  # empty first column
for folder in "$@"; do
    [ ! -d "$folder" ] && { echo "not folder: $folder" >&2; continue; }
    (
    flattened_folder_name="${folder//\//_}"
    bfile="${tempdir}/${flattened_folder_name}"
    process_batch_run -o "${bfile}" "$folder"/*
    echo "$flattened_folder_name" > "${bfile}.dat"
    cut -f2 "$bfile"             >> "${bfile}.dat"
    mutex "${tempdir}/once" && cut -f1 "${bfile}" >> "$labelfile"
    )&
done

wait

paste "$labelfile" "$tempdir"/*.dat > "$outfile"
