#!/bin/bash
# timechart.sh: generate barcharts for a set of files generated by tabulate.sh

width=0.5
gap=$(bc <<< "$width * 2")
plotfile="/var/tmp/plotfile"
temp="/var/tmp/temp.dat"

for file in "$@"; do
    cat  > "$plotfile" <<HEAD
set boxwidth $width
set style fill solid
set style line 1 lc rgb "#ff9999"
set style line 2 lc rgb "#dd8080"
set yrange [0:]
unset key
HEAD

    # script 1: generate x labels from string preceding data
    # in format, ("label" x_coord, ...)
    awk '
    BEGIN {
        w = '$width' ; g = '$gap' ; s = g+w
        printf "set xtics ("
    }
    {
        N = NF - 2
        i = NR - 1
        array[$1] = ((2*i+1)*N*w)*0.5 + i*s
    }
    END {
        for (name in array) {
            pname = name
            gsub(/_/," ",pname)
            printf("\"%s\" %G,", pname, array[name])
        }
        printf ")\n"
    }' $file >> $plotfile

    # add plot commands
    cat >> $plotfile <<PLOT
plot "$temp" every 2    u 1:2      w boxes ls 1, \\
     "$temp" every 2::1 u 1:2      w boxes ls 2, \\
     "$temp"            u 1:(20):2 w labels font ",5"
PLOT

    # add position column to data
    awk '
    BEGIN { OFS="\t"; x = 0; w = '$width'}
    {
        for (i = 2; i <= NF; ++i) {
            print " "x, $i
            x+=w
        }
        x+='$gap'
    }
    END { print "e" }
    ' $file > $temp

    gnuplot -p $plotfile
done
